name: graph
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - numpy
  - python
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
  - pip:
      - datasets
      - einops
      - fsspec==2022.2.0
      - h3==3.7.3
      - huggingface-hub
      - pandas
      - pyarrow
      - responses
      - pysolar
      - pytorch-lightning
      - deepspeed
      - click
